
HEADERS_ENG: dict = {
    ("@odata.etag",): "@odata.etag",
    ("kc_customsservices",): "kc_customsservices",
    ("kc_interviewformcode",): "kc_interviewformcode",
    ("kc_question3",): "kc_question3",
    ("kc_question2",): "kc_question2",
    ("kc_question1",): "kc_question1",
    ("kc_question7",): "kc_question7",
    ("kc_question6",): "kc_question6",
    ("kc_question5",): "kc_question5",
    ("kc_question4",): "kc_question4",
    ("statecode",): "statecode",
    ("kc_answer11",): "kc_answer11",
    ("_kc_managerretentionid_value",): "_kc_managerretentionid_value",
    ("kc_customerstatuscode",): "kc_customerstatuscode",
    ("kc_signofrelationship",): "kc_signofrelationship",
    ("_kc_accountid_value",): "_kc_accountid_value",
    ("_owningbusinessunit_value",): "_owningbusinessunit_value",
    ("_owninguser_value",): "_owninguser_value",
    ("_kc_businessunitid_value",): "_kc_businessunitid_value",
    ("_kc_contactid_value",): "_kc_contactid_value",
    ("kc_train",): "kc_train",
    ("kc_interviewid",): "kc_interviewid",
    ("_ownerid_value",): "_ownerid_value",
    ("kc_jobtitle",): "kc_jobtitle",
    ("kc_portservices",): "kc_portservices",
    ("kc_ratingcode",): "kc_ratingcode",
    ("kc_other",): "kc_other",
    ("kc_auto",): "kc_auto",
    ("timezoneruleversionnumber",): "timezoneruleversionnumber",
    ("statuscode",): "statuscode",
    ("createdon",): "createdon",
    ("kc_inn",): "kc_inn",
    ("versionnumber",): "versionnumber",
    ("modifiedon",): "modifiedon",
    ("kc_internationalcarriage",): "kc_internationalcarriage",
    ("kc_feedback",): "kc_feedback",
    ("kc_interviewdate",): "kc_interviewdate",
    ("kc_name",): "kc_name",
    ("kc_offdockterminalservices",): "kc_offdockterminalservices",
    ("kc_email",): "kc_email",
    ("kc_phonenumber",): "kc_phonenumber",
    ("kc_question11",): "kc_question11",
    ("kc_needforcorrectiveaction",): "kc_needforcorrectiveaction",
    ("_modifiedby_value",): "_modifiedby_value",
    ("_createdby_value",): "_createdby_value",
    ("kc_formpassedtohead",): "kc_formpassedtohead",
    ("kc_needreinterview",): "kc_needreinterview",
    ("kc_typecustomercode",): "kc_typecustomercode",
    ("kc_interviewtypecode",): "kc_interviewtypecode",
    ("kc_answer1",): "kc_answer1",
    ("kc_answer3",): "kc_answer3",
    ("kc_answer2",): "kc_answer2",
    ("kc_answer5",): "kc_answer5",
    ("kc_answer4",): "kc_answer4",
    ("kc_answer7",): "kc_answer7",
    ("kc_answer6",): "kc_answer6",
    ("_kc_userid_value",): "_kc_userid_value",
    ("kc_comment10",): "kc_comment10",
    ("kc_answer8",): "kc_answer8",
    ("kc_comment8",): "kc_comment8",
    ("kc_workphonenumber",): "kc_workphonenumber",
    ("kc_question10",): "kc_question10",
    ("kc_comment7",): "kc_comment7",
    ("_owningteam_value",): "_owningteam_value",
    ("kc_comment12",): "kc_comment12",
    ("kc_question12",): "kc_question12",
    ("kc_answer9",): "kc_answer9",
    ("kc_openingslogans",): "kc_openingslogans",
    ("kc_comment6",): "kc_comment6",
    ("_kc_campaignid_value",): "_kc_campaignid_value",
    ("kc_answer12",): "kc_answer12",
    ("kc_comment11",): "kc_comment11",
    ("rn_comment14",): "rn_comment14",
    ("rn_question14",): "rn_question14",
    ("kc_interviewtype",): "kc_interviewtype",
    ("kc_comment2",): "kc_comment2",
    ("kc_comment3",): "kc_comment3",
    ("overriddencreatedon",): "overriddencreatedon",
    ("_rn_incident_value",): "_rn_incident_value",
    ("kc_answer10",): "kc_answer10",
    ("kc_comment1",): "kc_comment1",
    ("kc_comment5",): "kc_comment5",
    ("kc_description",): "kc_description",
    ("utcconversiontimezonecode",): "utcconversiontimezonecode",
    ("_createdonbehalfby_value",): "_createdonbehalfby_value",
    ("kc_question8",): "kc_question8",
    ("kc_comment4",): "kc_comment4",
    ("importsequencenumber",): "importsequencenumber",
    ("kc_finalslogans",): "kc_finalslogans",
    ("kc_whenneedreinterview",): "kc_whenneedreinterview",
    ("kc_comment9",): "kc_comment9",
    ("rn_answer14",): "rn_answer14",
    ("kc_question9",): "kc_question9",
    ("_modifiedonbehalfby_value",): "_modifiedonbehalfby_value"
}

LIST_OF_FLOAT_TYPE: list = []
LIST_OF_BOOL_TYPE: list = [
    "kc_feedback",
    "kc_needforcorrectiveaction",
    "kc_formpassedtohead",
    "kc_needreinterview"
]
LIST_OF_INT_TYPE: list = [
    "kc_customsservices",
    "kc_interviewformcode",
    "statecode",
    "kc_customerstatuscode",
    "kc_signofrelationship",
    "kc_train",
    "kc_portservices",
    "kc_ratingcode",
    "kc_other",
    "kc_auto",
    "timezoneruleversionnumber",
    "statuscode",
    "kc_inn",
    "versionnumber",
    "kc_internationalcarriage",
    "kc_offdockterminalservices",
    "kc_typecustomercode",
    "kc_interviewtypecode",
    "kc_interviewtype"
]
LIST_OF_DATE_TYPE: list = [
    "createdon",
    "modifiedon",
    "kc_interviewdate"
]
