
HEADERS_ENG: dict = {
    ("@odata.etag",): "@odata.etag",
    ("systemuserid",): "systemuserid",
    ("accessmode",): "accessmode",
    ("kc_guidisr",): "kc_guidisr",
    ("issyncwithdirectory",): "issyncwithdirectory",
    ("address1_addressid",): "address1_addressid",
    ("incomingemaildeliverymethod",): "incomingemaildeliverymethod",
    ("internalemailaddress",): "internalemailaddress",
    ("domainname",): "domainname",
    ("_queueid_value",): "_queueid_value",
    ("isintegrationuser",): "isintegrationuser",
    ("createdon",): "createdon",
    ("_calendarid_value",): "_calendarid_value",
    ("fullname",): "fullname",
    ("_businessunitid_value",): "_businessunitid_value",
    ("invitestatuscode",): "invitestatuscode",
    ("defaultodbfoldername",): "defaultodbfoldername",
    ("caltype",): "caltype",
    ("modifiedon",): "modifiedon",
    ("defaultfilterspopulated",): "defaultfilterspopulated",
    ("outgoingemaildeliverymethod",): "outgoingemaildeliverymethod",
    ("emailrouteraccessapproval",): "emailrouteraccessapproval",
    ("versionnumber",): "versionnumber",
    ("kc_initialseng",): "kc_initialseng",
    ("mobilephone",): "mobilephone",
    ("setupuser",): "setupuser",
    ("userlicensetype",): "userlicensetype",
    ("_modifiedby_value",): "_modifiedby_value",
    ("organizationid",): "organizationid",
    ("middlename",): "middlename",
    ("lastname",): "lastname",
    ("isemailaddressapprovedbyo365admin",): "isemailaddressapprovedbyo365admin",
    ("firstname",): "firstname",
    ("yomifullname",): "yomifullname",
    ("kc_guidukt",): "kc_guidukt",
    ("isdisabled",): "isdisabled",
    ("address2_addressid",): "address2_addressid",
    ("_defaultmailbox_value",): "_defaultmailbox_value",
    ("islicensed",): "islicensed",
    ("ownerid",): "ownerid",
    ("_createdby_value",): "_createdby_value",
    ("preferredaddresscode",): "preferredaddresscode",
    ("nickname",): "nickname",
    ("azureactivedirectoryobjectid",): "azureactivedirectoryobjectid",
    ("kc_fullnameeng",): "kc_fullnameeng",
    ("address2_stateorprovince",): "address2_stateorprovince",
    ("applicationiduri",): "applicationiduri",
    ("address1_county",): "address1_county",
    ("address2_country",): "address2_country",
    ("address2_postofficebox",): "address2_postofficebox",
    ("preferredphonecode",): "preferredphonecode",
    ("yammeruserid",): "yammeruserid",
    ("title",): "title",
    ("trx_phone_calls_recording",): "trx_phone_calls_recording",
    ("employeeid",): "employeeid",
    ("_territoryid_value",): "_territoryid_value",
    ("jobtitle",): "jobtitle",
    ("skills",): "skills",
    ("rn_guid",): "rn_guid",
    ("address2_composite",): "address2_composite",
    ("address1_postalcode",): "address1_postalcode",
    ("entityimage",): "entityimage",
    ("windowsliveid",): "windowsliveid",
    ("address1_line3",): "address1_line3",
    ("disabledreason",): "disabledreason",
    ("address2_utcoffset",): "address2_utcoffset",
    ("address1_line2",): "address1_line2",
    ("address1_city",): "address1_city",
    ("personalemailaddress",): "personalemailaddress",
    ("_kc_cfoid_value",): "_kc_cfoid_value",
    ("address1_telephone2",): "address1_telephone2",
    ("_createdonbehalfby_value",): "_createdonbehalfby_value",
    ("address1_longitude",): "address1_longitude",
    ("sharepointemailaddress",): "sharepointemailaddress",
    ("yomifirstname",): "yomifirstname",
    ("exchangerate",): "exchangerate",
    ("address1_shippingmethodcode",): "address1_shippingmethodcode",
    ("yomimiddlename",): "yomimiddlename",
    ("address2_line2",): "address2_line2",
    ("address1_line1",): "address1_line1",
    ("address1_telephone1",): "address1_telephone1",
    ("traversedpath",): "traversedpath",
    ("address1_country",): "address1_country",
    ("yomilastname",): "yomilastname",
    ("address2_latitude",): "address2_latitude",
    ("address2_fax",): "address2_fax",
    ("address1_composite",): "address1_composite",
    ("trx_extension",): "trx_extension",
    ("address1_latitude",): "address1_latitude",
    ("entityimage_timestamp",): "entityimage_timestamp",
    ("photourl",): "photourl",
    ("_siteid_value",): "_siteid_value",
    ("_transactioncurrencyid_value",): "_transactioncurrencyid_value",
    ("passportlo",): "passportlo",
    ("_mobileofflineprofileid_value",): "_mobileofflineprofileid_value",
    ("address1_name",): "address1_name",
    ("address2_telephone2",): "address2_telephone2",
    ("_parentsystemuserid_value",): "_parentsystemuserid_value",
    ("stageid",): "stageid",
    ("address2_longitude",): "address2_longitude",
    ("salutation",): "salutation",
    ("yammeremailaddress",): "yammeremailaddress",
    ("address2_city",): "address2_city",
    ("entityimageid",): "entityimageid",
    ("address1_addresstypecode",): "address1_addresstypecode",
    ("address2_county",): "address2_county",
    ("address2_line1",): "address2_line1",
    ("address2_upszone",): "address2_upszone",
    ("address1_utcoffset",): "address1_utcoffset",
    ("_positionid_value",): "_positionid_value",
    ("address2_shippingmethodcode",): "address2_shippingmethodcode",
    ("passporthi",): "passporthi",
    ("address1_telephone3",): "address1_telephone3",
    ("address2_postalcode",): "address2_postalcode",
    ("address2_telephone1",): "address2_telephone1",
    ("entityimage_url",): "entityimage_url",
    ("processid",): "processid",
    ("governmentid",): "governmentid",
    ("_modifiedonbehalfby_value",): "_modifiedonbehalfby_value",
    ("address2_line3",): "address2_line3",
    ("utcconversiontimezonecode",): "utcconversiontimezonecode",
    ("homephone",): "homephone",
    ("trx_lic",): "trx_lic",
    ("preferredemailcode",): "preferredemailcode",
    ("address2_name",): "address2_name",
    ("overriddencreatedon",): "overriddencreatedon",
    ("address1_upszone",): "address1_upszone",
    ("importsequencenumber",): "importsequencenumber",
    ("mobilealertemail",): "mobilealertemail",
    ("address2_addresstypecode",): "address2_addresstypecode",
    ("address1_fax",): "address1_fax",
    ("address2_telephone3",): "address2_telephone3",
    ("address1_postofficebox",): "address1_postofficebox",
    ("address1_stateorprovince",): "address1_stateorprovince",
    ("displayinserviceviews",): "displayinserviceviews",
    ("timezoneruleversionnumber",): "timezoneruleversionnumber",
    ("applicationid",): "applicationid"
}


LIST_OF_FLOAT_TYPE: list = [
    "exchangerate"
]
LIST_OF_BOOL_TYPE: list = [
    "issyncwithdirectory",
    "isintegrationuser",
    "defaultfilterspopulated",
    "setupuser",
    "isemailaddressapprovedbyo365admin",
    "isdisabled",
    "islicensed",
    "trx_phone_calls_recording",
    "trx_lic",
    "displayinserviceviews"
]
LIST_OF_INT_TYPE: list = [
    "accessmode",
    "incomingemaildeliverymethod",
    "invitestatuscode",
    "caltype",
    "outgoingemaildeliverymethod",
    "emailrouteraccessapproval",
    "versionnumber",
    "userlicensetype",
    "preferredaddresscode",
    "preferredphonecode",
    "address1_postalcode",
    "address1_shippingmethodcode",
    "trx_extension",
    "entityimage_timestamp",
    "address1_addresstypecode",
    "address2_shippingmethodcode",
    "preferredemailcode",
    "address2_addresstypecode"
]
LIST_OF_DATE_TYPE: list = [
    "createdon",
    "modifiedon"
]
