
HEADERS_ENG: dict = {
    ("@odata.etag",): "odata.etag",
    ("inheritancemask",): "inheritancemask",
    ("address2_addressid",): "address2_addressid",
    ("modifiedon",): "modifiedon",
    ("createdon",): "createdon",
    ("versionnumber",): "versionnumber",
    ("isdisabled",): "isdisabled",
    ("name",): "name",
    ("_organizationid_value",): "_organizationid_value",
    ("businessunitid",): "businessunitid",
    ("address1_addressid",): "address1_addressid",
    ("address1_line2",): "address1_line2",
    ("address1_stateorprovince",): "address1_stateorprovince",
    ("address1_addresstypecode",): "address1_addresstypecode",
    ("address2_addresstypecode",): "address2_addresstypecode",
    ("_modifiedonbehalfby_value",): "_modifiedonbehalfby_value",
    ("creditlimit",): "creditlimit",
    ("exchangerate",): "exchangerate",
    ("emailaddress",): "emailaddress",
    ("_modifiedby_value",): "_modifiedby_value",
    ("stockexchange",): "stockexchange",
    ("address1_telephone1",): "address1_telephone1",
    ("address2_shippingmethodcode",): "address2_shippingmethodcode",
    ("address2_country",): "address2_country",
    ("address2_name",): "address2_name",
    ("tickersymbol",): "tickersymbol",
    ("address2_utcoffset",): "address2_utcoffset",
    ("address2_latitude",): "address2_latitude",
    ("_parentbusinessunitid_value",): "_parentbusinessunitid_value",
    ("address2_fax",): "address2_fax",
    ("importsequencenumber",): "importsequencenumber",
    ("picture",): "picture",
    ("address1_county",): "address1_county",
    ("address2_line1",): "address2_line1",
    ("_createdonbehalfby_value",): "_createdonbehalfby_value",
    ("address2_telephone2",): "address2_telephone2",
    ("divisionname",): "divisionname",
    ("websiteurl",): "websiteurl",
    ("address2_telephone1",): "address2_telephone1",
    ("address2_postofficebox",): "address2_postofficebox",
    ("fileasname",): "fileasname",
    ("address1_telephone3",): "address1_telephone3",
    ("address1_line1",): "address1_line1",
    ("address2_line3",): "address2_line3",
    ("address1_city",): "address1_city",
    ("utcoffset",): "utcoffset",
    ("address2_longitude",): "address2_longitude",
    ("address1_shippingmethodcode",): "address1_shippingmethodcode",
    ("address1_latitude",): "address1_latitude",
    ("costcenter",): "costcenter",
    ("address1_utcoffset",): "address1_utcoffset",
    ("address2_line2",): "address2_line2",
    ("address1_fax",): "address1_fax",
    ("address1_name",): "address1_name",
    ("address1_line3",): "address1_line3",
    ("address2_telephone3",): "address2_telephone3",
    ("address1_longitude",): "address1_longitude",
    ("address2_upszone",): "address2_upszone",
    ("_calendarid_value",): "_calendarid_value",
    ("address2_county",): "address2_county",
    ("address2_city",): "address2_city",
    ("address1_postofficebox",): "address1_postofficebox",
    ("workflowsuspended",): "workflowsuspended",
    ("address1_postalcode",): "address1_postalcode",
    ("_createdby_value",): "_createdby_value",
    ("_transactioncurrencyid_value",): "_transactioncurrencyid_value",
    ("address1_telephone2",): "address1_telephone2",
    ("address1_upszone",): "address1_upszone",
    ("address2_stateorprovince",): "address2_stateorprovince",
    ("overriddencreatedon",): "overriddencreatedon",
    ("address2_postalcode",): "address2_postalcode",
    ("address1_country",): "address1_country",
    ("description",): "description",
    ("disabledreason",): "disabledreason",
    ("ftpsiteurl",): "ftpsiteurl"
}

LIST_OF_FLOAT_TYPE: list = [
    "exchangerate"
]
LIST_OF_BOOL_TYPE: list = [
    "isdisabled",
    "workflowsuspended"
]
LIST_OF_INT_TYPE: list = [
    "inheritancemask",
    "versionnumber",
    "address1_addresstypecode",
    "address2_addresstypecode",
    "address2_shippingmethodcode",
    "address1_shippingmethodcode"
]
LIST_OF_DATE_TYPE: list = [
    "createdon",
    "modifiedon"
]
