
HEADERS_ENG: dict = {
    ("@odata.etag",): "odata.etag",
    ("kc_directioncode",): "kc_directioncode",
    ("prioritycode",): "prioritycode",
    ("completeinternalreview",): "completeinternalreview",
    ("stepname",): "stepname",
    ("rn_lastactivitydate",): "rn_lastactivitydate",
    ("filedebrief",): "filedebrief",
    ("kc_guidukt",): "kc_guidukt",
    ("confirminterest",): "confirminterest",
    ("captureproposalfeedback",): "captureproposalfeedback",
    ("exchangerate",): "exchangerate",
    ("opportunityid",): "opportunityid",
    ("_parentcontactid_value",): "_parentcontactid_value",
    ("identifycompetitors",): "identifycompetitors",
    ("_parentaccountid_value",): "_parentaccountid_value",
    ("name",): "name",
    ("decisionmaker",): "decisionmaker",
    ("kc_sendtoukt",): "kc_sendtoukt",
    ("isrevenuesystemcalculated",): "isrevenuesystemcalculated",
    ("_transactioncurrencyid_value",): "_transactioncurrencyid_value",
    ("kc_potencialprofitperunit",): "kc_potencialprofitperunit",
    ("_owninguser_value",): "_owninguser_value",
    ("totalamount",): "totalamount",
    ("presentproposal",): "presentproposal",
    ("createdon",): "createdon",
    ("kc_potencialteu",): "kc_potencialteu",
    ("_ownerid_value",): "_ownerid_value",
    ("sendthankyounote",): "sendthankyounote",
    ("identifycustomercontacts",): "identifycustomercontacts",
    ("stageid",): "stageid",
    ("traversedpath",): "traversedpath",
    ("rn_lastactivitydate_date",): "rn_lastactivitydate_date",
    ("evaluatefit",): "evaluatefit",
    ("totalamountlessfreight",): "totalamountlessfreight",
    ("kc_potencialamountwithvat",): "kc_potencialamountwithvat",
    ("totallineitemdiscountamount",): "totallineitemdiscountamount",
    ("totalamountlessfreight_base",): "totalamountlessfreight_base",
    ("totaldiscountamount",): "totaldiscountamount",
    ("processid",): "processid",
    ("statuscode",): "statuscode",
    ("kc_potencialamount",): "kc_potencialamount",
    ("totaltax_base",): "totaltax_base",
    ("totallineitemamount_base",): "totallineitemamount_base",
    ("totalamount_base",): "totalamount_base",
    ("developproposal",): "developproposal",
    ("versionnumber",): "versionnumber",
    ("description",): "description",
    ("modifiedon",): "modifiedon",
    ("resolvefeedback",): "resolvefeedback",
    ("totaltax",): "totaltax",
    ("totaldiscountamount_base",): "totaldiscountamount_base",
    ("rn_lastactivitydate_state",): "rn_lastactivitydate_state",
    ("_modifiedby_value",): "_modifiedby_value",
    ("presentfinalproposal",): "presentfinalproposal",
    ("_createdby_value",): "_createdby_value",
    ("pricingerrorcode",): "pricingerrorcode",
    ("salesstagecode",): "salesstagecode",
    ("totallineitemdiscountamount_base",): "totallineitemdiscountamount_base",
    ("identifypursuitteam",): "identifypursuitteam",
    ("participatesinworkflow",): "participatesinworkflow",
    ("statecode",): "statecode",
    ("_owningbusinessunit_value",): "_owningbusinessunit_value",
    ("pursuitdecision",): "pursuitdecision",
    ("opportunityratingcode",): "opportunityratingcode",
    ("_customerid_value",): "_customerid_value",
    ("totallineitemamount",): "totallineitemamount",
    ("completefinalproposal",): "completefinalproposal",
    ("schedulefollowup_prospect",): "schedulefollowup_prospect",
    ("kc_loststatuscode",): "kc_loststatuscode",
    ("actualvalue",): "actualvalue",
    ("freightamount",): "freightamount",
    ("kc_projectnumber",): "kc_projectnumber",
    ("timezoneruleversionnumber",): "timezoneruleversionnumber",
    ("utcconversiontimezonecode",): "utcconversiontimezonecode",
    ("rn_paymentrate",): "rn_paymentrate",
    ("rn_initiatives",): "rn_initiatives",
    ("freightamount_base",): "freightamount_base",
    ("timespentbymeonemailandmeetings",): "timespentbymeonemailandmeetings",
    ("salesstage",): "salesstage",
    ("actualclosedate",): "actualclosedate",
    ("actualvalue_base",): "actualvalue_base",
    ("quotecomments",): "quotecomments",
    ("kc_reason",): "kc_reason",
    ("_owningteam_value",): "_owningteam_value",
    ("_slainvokedid_value",): "_slainvokedid_value",
    ("discountamount",): "discountamount",
    ("_pricelevelid_value",): "_pricelevelid_value",
    ("budgetamount",): "budgetamount",
    ("closeprobability",): "closeprobability",
    ("budgetstatus",): "budgetstatus",
    ("estimatedvalue_base",): "estimatedvalue_base",
    ("estimatedclosedate",): "estimatedclosedate",
    ("need",): "need",
    ("lastonholdtime",): "lastonholdtime",
    ("_contactid_value",): "_contactid_value",
    ("rn_accounting_system",): "rn_accounting_system",
    ("importsequencenumber",): "importsequencenumber",
    ("_modifiedonbehalfby_value",): "_modifiedonbehalfby_value",
    ("_originatingleadid_value",): "_originatingleadid_value",
    ("kc_datenexttender",): "kc_datenexttender",
    ("purchaseprocess",): "purchaseprocess",
    ("stepid",): "stepid",
    ("onholdtime",): "onholdtime",
    ("discountpercentage",): "discountpercentage",
    ("proposedsolution",): "proposedsolution",
    ("schedulefollowup_qualify",): "schedulefollowup_qualify",
    ("customerneed",): "customerneed",
    ("overriddencreatedon",): "overriddencreatedon",
    ("_accountid_value",): "_accountid_value",
    ("finaldecisiondate",): "finaldecisiondate",
    ("estimatedvalue",): "estimatedvalue",
    ("_campaignid_value",): "_campaignid_value",
    ("kc_plandateapplication",): "kc_plandateapplication",
    ("_slaid_value",): "_slaid_value",
    ("discountamount_base",): "discountamount_base",
    ("kc_guidisr",): "kc_guidisr",
    ("purchasetimeframe",): "purchasetimeframe",
    ("budgetamount_base",): "budgetamount_base",
    ("qualificationcomments",): "qualificationcomments",
    ("_createdonbehalfby_value",): "_createdonbehalfby_value",
    ("currentsituation",): "currentsituation",
    ("customerpainpoints",): "customerpainpoints",
    ("scheduleproposalmeeting",): "scheduleproposalmeeting",
    ("initialcommunication",): "initialcommunication",
    ("timeline",): "timeline"
}


LIST_OF_FLOAT_TYPE: list = [
    "exchangerate",
    "kc_potencialprofitperunit",
    "totalamount",
    "totalamountlessfreight",
    "kc_potencialamountwithvat",
    "totallineitemdiscountamount",
    "totalamountlessfreight_base",
    "totaldiscountamount",
    "kc_potencialamount",
    "totaltax_base",
    "totallineitemamount_base",
    "totalamount_base",
    "totaltax",
    "totaldiscountamount_base",
    "totallineitemdiscountamount_base",
    "totallineitemamount",
    "estimatedvalue_base",
    "estimatedvalue"
]
LIST_OF_BOOL_TYPE: list = [
    "exchangerate",
    "kc_potencialprofitperunit",
    "totalamount",
    "totalamountlessfreight",
    "kc_potencialamountwithvat",
    "totallineitemdiscountamount",
    "totalamountlessfreight_base",
    "totaldiscountamount",
    "kc_potencialamount",
    "totaltax_base",
    "totallineitemamount_base",
    "totalamount_base",
    "totaltax",
    "totaldiscountamount_base",
    "totallineitemdiscountamount_base",
    "totallineitemamount",
    "estimatedvalue_base",
    "estimatedvalue"
]
LIST_OF_INT_TYPE: list = [
    "kc_directioncode",
    "prioritycode",
    "kc_potencialteu",
    "statuscode",
    "versionnumber",
    "rn_lastactivitydate_state",
    "pricingerrorcode",
    "salesstagecode",
    "statecode",
    "opportunityratingcode",
    "kc_loststatuscode",
    "timezoneruleversionnumber",
    "salesstage",
    "rn_accounting_system"
]
LIST_OF_DATE_TYPE: list = [
    "rn_lastactivitydate",
    "createdon",
    "rn_lastactivitydate_date",
    "modifiedon",
    "actualclosedate",
    "estimatedclosedate",
    "kc_datenexttender"
]
