
HEADERS_ENG: dict = {
    ("@odata.etag",): "@odata.etag",
    ("confirminterest",): "confirminterest",
    ("statecode",): "statecode",
    ("statuscode",): "statuscode",
    ("address2_shippingmethodcode",): "address2_shippingmethodcode",
    ("address1_addressid",): "address1_addressid",
    ("leadqualitycode",): "leadqualitycode",
    ("donotbulkemail",): "donotbulkemail",
    ("salesstagecode",): "salesstagecode",
    ("donotsendmm",): "donotsendmm",
    ("leadid",): "leadid",
    ("emailaddress1",): "emailaddress1",
    ("_owningteam_value",): "_owningteam_value",
    ("fullname",): "fullname",
    ("address1_addresstypecode",): "address1_addresstypecode",
    ("subject",): "subject",
    ("donotpostalmail",): "donotpostalmail",
    ("_ownerid_value",): "_ownerid_value",
    ("modifiedon",): "modifiedon",
    ("stageid",): "stageid",
    ("donotemail",): "donotemail",
    ("donotphone",): "donotphone",
    ("address2_addresstypecode",): "address2_addresstypecode",
    ("kc_convertingemail",): "kc_convertingemail",
    ("versionnumber",): "versionnumber",
    ("createdon",): "createdon",
    ("prioritycode",): "prioritycode",
    ("traversedpath",): "traversedpath",
    ("address1_shippingmethodcode",): "address1_shippingmethodcode",
    ("description",): "description",
    ("leadsourcecode",): "leadsourcecode",
    ("_modifiedby_value",): "_modifiedby_value",
    ("decisionmaker",): "decisionmaker",
    ("preferredcontactmethodcode",): "preferredcontactmethodcode",
    ("_owningbusinessunit_value",): "_owningbusinessunit_value",
    ("lastname",): "lastname",
    ("yomifullname",): "yomifullname",
    ("donotfax",): "donotfax",
    ("merged",): "merged",
    ("_createdby_value",): "_createdby_value",
    ("processid",): "processid",
    ("address2_addressid",): "address2_addressid",
    ("evaluatefit",): "evaluatefit",
    ("participatesinworkflow",): "participatesinworkflow",
    ("address1_name",): "address1_name",
    ("rn_tenderorderdate",): "rn_tenderorderdate",
    ("address1_county",): "address1_county",
    ("address1_telephone2",): "address1_telephone2",
    ("address1_city",): "address1_city",
    ("address1_telephone1",): "address1_telephone1",
    ("utcconversiontimezonecode",): "utcconversiontimezonecode",
    ("address2_country",): "address2_country",
    ("address2_postofficebox",): "address2_postofficebox",
    ("address2_city",): "address2_city",
    ("budgetamount_base",): "budgetamount_base",
    ("estimatedvalue",): "estimatedvalue",
    ("lastusedincampaign",): "lastusedincampaign",
    ("rn_tenderorderprice_base",): "rn_tenderorderprice_base",
    ("budgetstatus",): "budgetstatus",
    ("address1_line3",): "address1_line3",
    ("estimatedclosedate",): "estimatedclosedate",
    ("rn_deadline",): "rn_deadline",
    ("salesstage",): "salesstage",
    ("initialcommunication",): "initialcommunication",
    ("followemail",): "followemail",
    ("rn_tenderresult",): "rn_tenderresult",
    ("estimatedamount_base",): "estimatedamount_base",
    ("budgetamount",): "budgetamount",
    ("rn_suspectspam",): "rn_suspectspam",
    ("industrycode",): "industrycode",
    ("telephone3",): "telephone3",
    ("address1_country",): "address1_country",
    ("middlename",): "middlename",
    ("exchangerate",): "exchangerate",
    ("overriddencreatedon",): "overriddencreatedon",
    ("mobilephone",): "mobilephone",
    ("fax",): "fax",
    ("yomilastname",): "yomilastname",
    ("_accountid_value",): "_accountid_value",
    ("sic",): "sic",
    ("entityimageid",): "entityimageid",
    ("address1_composite",): "address1_composite",
    ("need",): "need",
    ("_owninguser_value",): "_owninguser_value",
    ("address1_upszone",): "address1_upszone",
    ("purchaseprocess",): "purchaseprocess",
    ("_createdonbehalfby_value",): "_createdonbehalfby_value",
    ("address1_postalcode",): "address1_postalcode",
    ("_parentcontactid_value",): "_parentcontactid_value",
    ("entityimage",): "entityimage",
    ("yomifirstname",): "yomifirstname",
    ("address1_stateorprovince",): "address1_stateorprovince",
    ("timespentbymeonemailandmeetings",): "timespentbymeonemailandmeetings",
    ("_customerid_value",): "_customerid_value",
    ("address1_postofficebox",): "address1_postofficebox",
    ("entityimage_url",): "entityimage_url",
    ("address2_county",): "address2_county",
    ("_originatingcaseid_value",): "_originatingcaseid_value",
    ("_contactid_value",): "_contactid_value",
    ("telephone2",): "telephone2",
    ("address2_line3",): "address2_line3",
    ("address2_line1",): "address2_line1",
    ("salutation",): "salutation",
    ("numberofemployees",): "numberofemployees",
    ("rn_tenderorderprice",): "rn_tenderorderprice",
    ("kc_directioncode",): "kc_directioncode",
    ("companyname",): "companyname",
    ("_qualifyingopportunityid_value",): "_qualifyingopportunityid_value",
    ("_slaid_value",): "_slaid_value",
    ("firstname",): "firstname",
    ("address1_latitude",): "address1_latitude",
    ("schedulefollowup_qualify",): "schedulefollowup_qualify",
    ("address2_latitude",): "address2_latitude",
    ("address1_line2",): "address1_line2",
    ("_masterid_value",): "_masterid_value",
    ("address2_fax",): "address2_fax",
    ("rn_tenderconclusion",): "rn_tenderconclusion",
    ("address2_telephone1",): "address2_telephone1",
    ("address1_telephone3",): "address1_telephone3",
    ("purchasetimeframe",): "purchasetimeframe",
    ("address2_line2",): "address2_line2",
    ("address2_upszone",): "address2_upszone",
    ("websiteurl",): "websiteurl",
    ("address2_postalcode",): "address2_postalcode",
    ("rn_tendertype",): "rn_tendertype",
    ("address2_name",): "address2_name",
    ("pager",): "pager",
    ("kc_saleschannelcode",): "kc_saleschannelcode",
    ("rn_spamcheckdate",): "rn_spamcheckdate",
    ("address2_telephone2",): "address2_telephone2",
    ("entityimage_timestamp",): "entityimage_timestamp",
    ("_campaignid_value",): "_campaignid_value",
    ("address1_fax",): "address1_fax",
    ("yomimiddlename",): "yomimiddlename",
    ("jobtitle",): "jobtitle",
    ("timezoneruleversionnumber",): "timezoneruleversionnumber",
    ("emailaddress2",): "emailaddress2",
    ("emailaddress3",): "emailaddress3",
    ("lastonholdtime",): "lastonholdtime",
    ("_relatedobjectid_value",): "_relatedobjectid_value",
    ("_modifiedonbehalfby_value",): "_modifiedonbehalfby_value",
    ("address1_utcoffset",): "address1_utcoffset",
    ("_transactioncurrencyid_value",): "_transactioncurrencyid_value",
    ("qualificationcomments",): "qualificationcomments",
    ("onholdtime",): "onholdtime",
    ("revenue",): "revenue",
    ("address2_stateorprovince",): "address2_stateorprovince",
    ("estimatedamount",): "estimatedamount",
    ("kc_industrycode",): "kc_industrycode",
    ("_slainvokedid_value",): "_slainvokedid_value",
    ("address1_longitude",): "address1_longitude",
    ("address2_utcoffset",): "address2_utcoffset",
    ("address2_composite",): "address2_composite",
    ("schedulefollowup_prospect",): "schedulefollowup_prospect",
    ("yomicompanyname",): "yomicompanyname",
    ("telephone1",): "telephone1",
    ("address2_telephone3",): "address2_telephone3",
    ("_parentaccountid_value",): "_parentaccountid_value",
    ("address2_longitude",): "address2_longitude",
    ("_rn_tenderplatform_value",): "_rn_tenderplatform_value",
    ("kc_isoverdue",): "kc_isoverdue",
    ("address1_line1",): "address1_line1",
    ("importsequencenumber",): "importsequencenumber",
    ("revenue_base",): "revenue_base"
}

LIST_OF_FLOAT_TYPE: list = [
    "exchangerate"
]
LIST_OF_BOOL_TYPE: list = [
    "confirminterest",
    "donotbulkemail",
    "donotsendmm",
    "donotpostalmail",
    "donotemail",
    "donotphone",
    "kc_convertingemail",
    "decisionmaker",
    "donotfax",
    "merged",
    "evaluatefit",
    "participatesinworkflow",
    "followemail",
    "kc_isoverdue"
]
LIST_OF_INT_TYPE: list = [
    "statecode",
    "statuscode",
    "address2_shippingmethodcode",
    "leadqualitycode",
    "salesstagecode",
    "address1_addresstypecode",
    "address2_addresstypecode",
    "versionnumber",
    "prioritycode",
    "address1_shippingmethodcode",
    "leadsourcecode",
    "preferredcontactmethodcode",
    "address1_postalcode",
    "kc_directioncode",
    "kc_saleschannelcode",
    "kc_industrycode"
]
LIST_OF_DATE_TYPE: list = [
    "createdon"
]
