
HEADERS_ENG: dict = {
    ("@odata.etag",): "odata.etag",
    ('kc_portservices',): "kc_portservices",
    ('kc_customsservices',): "kc_customsservices",
    ('kc_provider',): "kc_provider",
    ('address2_addresstypecode',): "address2_addresstypecode",
    ('merged',): "merged",
    ('rn_regnom',): "rn_regnom",
    ('kc_lastinterviewdate_state',): "kc_lastinterviewdate_state",
    ('rn_taxnumber',): "rn_taxnumber",
    ('kc_competitor',): "kc_competitor",
    ('territorycode',): "territorycode",
    ('emailaddress1',): "emailaddress1",
    ('exchangerate',): "exchangerate",
    ('rn_getbyinn',): "rn_getbyinn",
    ('rn_projects',): "rn_projects",
    ('name',): "name",
    ('websiteurl',): "websiteurl",
    ('kc_auto_state',): "kc_auto_state",
    ('kc_sendtoukt',): "kc_sendtoukt",
    ('kc_customsservices_date',): "kc_customsservices_date",
    ('_owningbusinessunit_value',): "_owningbusinessunit_value",
    ('_owninguser_value',): "_owninguser_value",
    ('_primarycontactid_value',): "_primarycontactid_value",
    ('address2_line1',): "address2_line1",
    ('address1_composite',): "address1_composite",
    ('donotpostalmail',): "donotpostalmail",
    ('accountratingcode',): "accountratingcode",
    ('marketingonly',): "marketingonly",
    ('rn_number',): "rn_number",
    ('donotphone',): "donotphone",
    ('preferredcontactmethodcode',): "preferredcontactmethodcode",
    ('_ownerid_value',): "_ownerid_value",
    ('accountclassificationcode',): "accountclassificationcode",
    ('kc_firstsalesorderdate_state',): "kc_firstsalesorderdate_state",
    ('customersizecode',): "customersizecode",
    ('kc_offdockterminalservices_state',): "kc_offdockterminalservices_state",
    ('kc_quantityinterview_state',): "kc_quantityinterview_state",
    ('rn_clientmonitoring',): "rn_clientmonitoring",
    ('kc_firstsalesorderdate_date',): "kc_firstsalesorderdate_date",
    ('trx_phone_calls_recording',): "trx_phone_calls_recording",
    ('donotemail',): "donotemail",
    ('kc_train_state',): "kc_train_state",
    ('address2_shippingmethodcode',): "address2_shippingmethodcode",
    ('kc_auto',): "kc_auto",
    ('kc_portservices_state',): "kc_portservices_state",
    ('address2_freighttermscode',): "address2_freighttermscode",
    ('statuscode',): "statuscode",
    ('createdon',): "createdon",
    ('rn_lastsalesorderdate_date',): "rn_lastsalesorderdate_date",
    ('_originatingleadid_value',): "_originatingleadid_value",
    ('kc_line',): "kc_line",
    ('rn_haslead',): "rn_haslead",
    ('kc_internationalcarriage',): "kc_internationalcarriage",
    ('donotsendmm',): "donotsendmm",
    ('donotfax',): "donotfax",
    ('kc_opfcode',): "kc_opfcode",
    ('donotbulkpostalmail',): "donotbulkpostalmail",
    ('versionnumber',): "versionnumber",
    ('openrevenue_date',): "openrevenue_date",
    ('address1_line1',): "address1_line1",
    ('kc_train_date',): "kc_train_date",
    ('modifiedon',): "modifiedon",
    ('creditonhold',): "creditonhold",
    ('telephone1',): "telephone1",
    ('kc_train',): "kc_train",
    ('kc_ruscon',): "kc_ruscon",
    ('_transactioncurrencyid_value',): "_transactioncurrencyid_value",
    ('kc_internationalcarriage_state',): "kc_internationalcarriage_state",
    ('accountid',): "accountid",
    ('kc_auto_date',): "kc_auto_date",
    ('kc_internationalcarriage_date',): "kc_internationalcarriage_date",
    ('kc_customsservices_state',): "kc_customsservices_state",
    ('_modifiedby_value',): "_modifiedby_value",
    ('kc_quantityinterview_date',): "kc_quantityinterview_date",
    ('followemail',): "followemail",
    ('businesstypecode',): "businesstypecode",
    ('_createdby_value',): "_createdby_value",
    ('kc_offdockterminalservices_date',): "kc_offdockterminalservices_date",
    ('kc_fullname',): "kc_fullname",
    ('donotbulkemail',): "donotbulkemail",
    ('rn_lastsalesorderdate_state',): "rn_lastsalesorderdate_state",
    ('kc_fullnameeng',): "kc_fullnameeng",
    ('kc_quantityinterview',): "kc_quantityinterview",
    ('rn_isnumber',): "rn_isnumber",
    ('address2_composite',): "address2_composite",
    ('kc_offdockterminalservices',): "kc_offdockterminalservices",
    ('address1_addressid',): "address1_addressid",
    ('participatesinworkflow',): "participatesinworkflow",
    ('statecode',): "statecode",
    ('address2_addressid',): "address2_addressid",
    ('kc_lastinterviewdate_date',): "kc_lastinterviewdate_date",
    ('kc_portservices_date',): "kc_portservices_date",
    ('shippingmethodcode',): "shippingmethodcode",
    ('opendeals_date',): "opendeals_date",
    ('openrevenue_state',): "openrevenue_state",
    ('rn_monitoringdate',): "rn_monitoringdate",
    ('telephone3',): "telephone3",
    ('openrevenue',): "openrevenue",
    ('address2_longitude',): "address2_longitude",
    ('address1_longitude',): "address1_longitude",
    ('emailaddress2',): "emailaddress2",
    ('address1_country',): "address1_country",
    ('rn_dokey',): "rn_dokey",
    ('lastusedincampaign',): "lastusedincampaign",
    ('address1_postofficebox',): "address1_postofficebox",
    ('_modifiedonbehalfby_value',): "_modifiedonbehalfby_value",
    ('preferredappointmenttimecode',): "preferredappointmenttimecode",
    ('timespentbymeonemailandmeetings',): "timespentbymeonemailandmeetings",
    ('address2_name',): "address2_name",
    ('address2_upszone',): "address2_upszone",
    ('primarysatoriid',): "primarysatoriid",
    ('entityimage_url',): "entityimage_url",
    ('timezoneruleversionnumber',): "timezoneruleversionnumber",
    ('kc_customerstatuscode',): "kc_customerstatuscode",
    ('c4crm_guiduktorganisation',): "c4crm_guiduktorganisation",
    ('address1_stateorprovince',): "address1_stateorprovince",
    ('_slaid_value',): "_slaid_value",
    ('kc_guiduktpayer',): "kc_guiduktpayer",
    ('address2_city',): "address2_city",
    ('address1_upszone',): "address1_upszone",
    ('stockexchange',): "stockexchange",
    ('entityimage',): "entityimage",
    ('_preferredserviceid_value',): "_preferredserviceid_value",
    ('_masterid_value',): "_masterid_value",
    ('address2_latitude',): "address2_latitude",
    ('address2_utcoffset',): "address2_utcoffset",
    ('telephone2',): "telephone2",
    ('paymenttermscode',): "paymenttermscode",
    ('_territoryid_value',): "_territoryid_value",
    ('_modifiedbyexternalparty_value',): "_modifiedbyexternalparty_value",
    ('entityimageid',): "entityimageid",
    ('kc_guiduktline',): "kc_guiduktline",
    ('_owningteam_value',): "_owningteam_value",
    ('fax',): "fax",
    ('stageid',): "stageid",
    ('utcconversiontimezonecode',): "utcconversiontimezonecode",
    ('marketcap_base',): "marketcap_base",
    ('onholdtime',): "onholdtime",
    ('address1_primarycontactname',): "address1_primarycontactname",
    ('yominame',): "yominame",
    ('_defaultpricelevelid_value',): "_defaultpricelevelid_value",
    ('ownershipcode',): "ownershipcode",
    ('address2_telephone2',): "address2_telephone2",
    ('address2_line3',): "address2_line3",
    ('_createdonbehalfby_value',): "_createdonbehalfby_value",
    ('kc_productdescription',): "kc_productdescription",
    ('_createdbyexternalparty_value',): "_createdbyexternalparty_value",
    ('kc_inn',): "kc_inn",
    ('kc_guiduktclient',): "kc_guiduktclient",
    ('overriddencreatedon',): "overriddencreatedon",
    ('address1_utcoffset',): "address1_utcoffset",
    ('primarytwitterid',): "primarytwitterid",
    ('ftpsiteurl',): "ftpsiteurl",
    ('sic',): "sic",
    ('address1_telephone2',): "address1_telephone2",
    ('tickersymbol',): "tickersymbol",
    ('rn_lastsalesorderdate',): "rn_lastsalesorderdate",
    ('address1_line2',): "address1_line2",
    ('numberofemployees',): "numberofemployees",
    ('kc_industrycode',): "kc_industrycode",
    ('aging60_base',): "aging60_base",
    ('revenue_base',): "revenue_base",
    ('openrevenue_base',): "openrevenue_base",
    ('industrycode',): "industrycode",
    ('address2_telephone3',): "address2_telephone3",
    ('address1_line3',): "address1_line3",
    ('address1_latitude',): "address1_latitude",
    ('address1_telephone1',): "address1_telephone1",
    ('accountnumber',): "accountnumber",
    ('entityimage_timestamp',): "entityimage_timestamp",
    ('_preferredsystemuserid_value',): "_preferredsystemuserid_value",
    ('kc_guidisrclient',): "kc_guidisrclient",
    ('address2_postalcode',): "address2_postalcode",
    ('kc_guidisrorganisation',): "kc_guidisrorganisation",
    ('preferredappointmentdaycode',): "preferredappointmentdaycode",
    ('kc_kpp',): "kc_kpp",
    ('processid',): "processid",
    ('creditlimit_base',): "creditlimit_base",
    ('address2_stateorprovince',): "address2_stateorprovince",
    ('_kc_managerretentionid_value',): "_kc_managerretentionid_value",
    ('kc_rate',): "kc_rate",
    ('emailaddress3',): "emailaddress3",
    ('importsequencenumber',): "importsequencenumber",
    ('_slainvokedid_value',): "_slainvokedid_value",
    ('aging90',): "aging90",
    ('sharesoutstanding',): "sharesoutstanding",
    ('opendeals_state',): "opendeals_state",
    ('kc_ogrn',): "kc_ogrn",
    ('address1_shippingmethodcode',): "address1_shippingmethodcode",
    ('kc_fixingmanagerdate',): "kc_fixingmanagerdate",
    ('address2_county',): "address2_county",
    ('description',): "description",
    ('kc_guidisrpayer',): "kc_guidisrpayer",
    ('aging60',): "aging60",
    ('marketcap',): "marketcap",
    ('accountcategorycode',): "accountcategorycode",
    ('aging30_base',): "aging30_base",
    ('address1_name',): "address1_name",
    ('opendeals',): "opendeals",
    ('aging30',): "aging30",
    ('address1_addresstypecode',): "address1_addresstypecode",
    ('address1_fax',): "address1_fax",
    ('traversedpath',): "traversedpath",
    ('_parentaccountid_value',): "_parentaccountid_value",
    ('address1_freighttermscode',): "address1_freighttermscode",
    ('address2_telephone1',): "address2_telephone1",
    ('address1_telephone3',): "address1_telephone3",
    ('kc_guiduktorganisation',): "kc_guiduktorganisation",
    ('address1_postalcode',): "address1_postalcode",
    ('_preferredequipmentid_value',): "_preferredequipmentid_value",
    ('rn_status',): "rn_status",
    ('kc_lastinterviewdate',): "kc_lastinterviewdate",
    ('address2_fax',): "address2_fax",
    ('lastonholdtime',): "lastonholdtime",
    ('kc_okpo',): "kc_okpo",
    ('customertypecode',): "customertypecode",
    ('_kc_whobroughtid_value',): "_kc_whobroughtid_value",
    ('kc_firstsalesorderdate',): "kc_firstsalesorderdate",
    ('creditlimit',): "creditlimit",
    ('aging90_base',): "aging90_base",
    ('address2_country',): "address2_country",
    ('address1_county',): "address1_county",
    ('address2_line2',): "address2_line2",
    ('revenue',): "revenue",
    ('rn_uid',): "rn_uid",
    ('address2_primarycontactname',): "address2_primarycontactname",
    ('address2_postofficebox',): "address2_postofficebox",
    ('address1_city',): "address1_city"
}


LIST_OF_FLOAT_TYPE: list = [
    "exchangerate",
    "revenue_base"
]
LIST_OF_BOOL_TYPE: list = [
    "trx_phone_calls_recording",
    "kc_provider",
    "kc_competitor",
    "kc_sendtoukt",
    "marketingonly",
    "rn_clientmonitoring",
    "kc_line",
    "rn_haslead",
    "donotbulkpostalmail",
    "creditonhold",
    "kc_ruscon",
    "rn_isnumber",
    "donotbulkemail",
    "donotsendmm",
    "donotpostalmail",
    "donotemail",
    "donotphone",
    "donotfax",
    "merged",
    "participatesinworkflow",
    "followemail",
]
LIST_OF_INT_TYPE: list = [
    "statecode",
    "kc_lastinterviewdate_state",
    "territorycode",
    "kc_auto_state",
    "accountratingcode",
    "accountclassificationcode",
    "kc_firstsalesorderdate_state",
    "customersizecode",
    "kc_offdockterminalservices_state",
    "kc_quantityinterview_state",
    "kc_train_state",
    "kc_portservices_state",
    "address2_freighttermscode",
    "kc_opfcode",
    "kc_internationalcarriage_state",
    "kc_customsservices_state",
    "businesstypecode",
    "rn_lastsalesorderdate_state",
    "kc_quantityinterview",
    "shippingmethodcode",
    "importsequencenumber",
    "rn_status",
    "statuscode",
    "versionnumber",
    "kc_customsservices",
    "kc_customerstatuscode",
    "kc_train",
    "kc_portservices",
    "kc_auto",
    "timezoneruleversionnumber",
    "kc_internationalcarriage",
    "kc_offdockterminalservices",
    "preferredcontactmethodcode",
    "kc_industrycode",
    "address1_postalcode",
    "address1_shippingmethodcode",
    "entityimage_timestamp",
    "address1_addresstypecode",
    "address2_shippingmethodcode",
    "address2_addresstypecode"
]
LIST_OF_DATE_TYPE: list = [
    "createdon",
    "modifiedon",
    "kc_customsservices_date",
    "kc_firstsalesorderdate_date",
    "rn_lastsalesorderdate_date",
    "openrevenue_date",
    "kc_train_date",
    "kc_auto_date",
    "kc_internationalcarriage_date",
    "kc_quantityinterview_date",
    "kc_offdockterminalservices_date",
    "kc_lastinterviewdate_date",
    "kc_portservices_date",
    "opendeals_date",
    "rn_monitoringdate",
    "rn_lastsalesorderdate",
    "kc_fixingmanagerdate",
    "kc_lastinterviewdate",
    "kc_firstsalesorderdate"
]
